### ISSUE TITLE
Interpolation Error Italic /circumflexacute

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Alegreya-Sans#2]
/circumflex acute interpolation error.

see:
Acircumflexacute Ecircumflexacute Ocircumflexacute acircumflexacute ecircumflexacute ocircumflexacute acircumflexacute.sc ecircumflexacute.sc ocircumflexacute.sc

![:circumflex acute Italic interp error](https://user-images.githubusercontent.com/6576107/68824590-5e31b180-0665-11ea-8205-4829e2750f67.png)

**Comment by cjdunn** [comment]
This issue will be resolved via my PR:
https://github.com/TypeNetwork/Alegreya-Sans/pull/5
