### ISSUE TITLE
'fi' ligature spacing bug

### ISSUE THREAD

**Issue by cosmicmocha** [TypeNetwork/Alegreya-Sans#6]
I was playing around and there seems to be an issue with the spacing on the fi ligature on all weights. Not sure if you're aware of it already, but I thought I'd just let you all know.
<br>
<img width="1439" alt="Screen Shot 2019-12-10 at 11 01 46 AM" src="https://user-images.githubusercontent.com/8769644/70546019-81ecf800-1b3c-11ea-8f0c-e9094dffd0cd.png">

**Comment by pichotta** [comment]
<img width="1246" alt="ligs Alegreya Sans" src="https://user-images.githubusercontent.com/6576107/75207340-67431c00-5746-11ea-9037-65f1ed05681a.png">
